//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class TACTIVITY_TYPE
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TACTIVITY_TYPE()
    {
        this.TORDER_ACTIVITY = new HashSet<TORDER_ACTIVITY>();
    }

    public short IDTYPE { get; set; }
    public byte IDTYPE_CATEGORY { get; set; }
    public string TYPE { get; set; }
    public Nullable<byte> TYPE_POS { get; set; }
    public bool TYPE_HIDE { get; set; }
    public System.DateTime CREATEDATE { get; set; }
    public System.DateTime MODIFYDATE { get; set; }

    public virtual TACTIVITY_TYPE_CATEGORY TACTIVITY_TYPE_CATEGORY { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<TORDER_ACTIVITY> TORDER_ACTIVITY { get; set; }
}

public partial class TACTIVITY_TYPE_CATEGORY
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TACTIVITY_TYPE_CATEGORY()
    {
        this.TACTIVITY_TYPE = new HashSet<TACTIVITY_TYPE>();
        this.TORDER_ACTIVITY = new HashSet<TORDER_ACTIVITY>();
    }

    public byte IDCATEGORY { get; set; }
    public int IDCATEGORY_COMPANY { get; set; }
    public string CATEGORY { get; set; }
    public string COLOR { get; set; }
    public bool CATEGORY_HIDE { get; set; }
    public System.DateTime CREATEDATE { get; set; }
    public System.DateTime MODIFYDATE { get; set; }
    public Nullable<byte> CATEGORY_POS { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<TACTIVITY_TYPE> TACTIVITY_TYPE { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<TORDER_ACTIVITY> TORDER_ACTIVITY { get; set; }
}

public partial class TCLIENT
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TCLIENT()
    {
        this.TCLIENT_ACCOUNTING = new HashSet<TCLIENT_ACCOUNTING>();
        this.TCLIENT_DATI_FATTURAZIONE = new HashSet<TCLIENT_DATI_FATTURAZIONE>();
        this.TCLIENT_BILL_DETAIL = new HashSet<TCLIENT_BILL_DETAIL>();
    }

    public int IDCLIENT { get; set; }
    public int IDCLIENT_CORPORATE { get; set; }
    public string NAME { get; set; }
    public string ALIAS { get; set; }
    public string ADDRESS { get; set; }
    public string LOCALITY { get; set; }
    public string ZIPCODE { get; set; }
    public Nullable<int> IDCLIENT_PROVINCE { get; set; }
    public Nullable<int> IDCLIENT_STATE { get; set; }
    public string VATNUMBER { get; set; }
    public string FISCAL_CODE { get; set; }
    public string PHONE1 { get; set; }
    public string PHONE2 { get; set; }
    public string MOBILE { get; set; }
    public string FAX { get; set; }
    public string EMAIL { get; set; }
    public string EMAIL2 { get; set; }
    public string EMAIL3 { get; set; }
    public string WEB { get; set; }
    public Nullable<bool> PRIVACY { get; set; }
    public string NOTE { get; set; }
    public Nullable<int> IDCLIENT_ACTIVITY { get; set; }
    public Nullable<int> IDCLIENT_SECTOR { get; set; }
    public string ACTIVITYNOTE { get; set; }
    public Nullable<int> IDCLIENT_EMPLOYEE { get; set; }
    public Nullable<int> IDCLIENT_COMPETITOR { get; set; }
    public Nullable<int> IDCLIENT_BUDGET { get; set; }
    public Nullable<int> IDCLIENT_TURNOVER { get; set; }
    public string GROUPNAME { get; set; }
    public bool CLIENT_NEWSLETTER { get; set; }
    public System.DateTime MACRODATE { get; set; }
    public Nullable<short> IDCLIENT_FONDO { get; set; }
    public string CODICEFATTURAZIONE { get; set; }

    public virtual TREGISTRY_PROVINCE TREGISTRY_PROVINCE { get; set; }
    public virtual TREGISTRY_STATE TREGISTRY_STATE { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<TCLIENT_ACCOUNTING> TCLIENT_ACCOUNTING { get; set; }
    public virtual TCLIENT TCLIENT1 { get; set; }
    public virtual TCLIENT TCLIENT2 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<TCLIENT_DATI_FATTURAZIONE> TCLIENT_DATI_FATTURAZIONE { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<TCLIENT_BILL_DETAIL> TCLIENT_BILL_DETAIL { get; set; }
}

public partial class TCLIENT_ACCOUNTING
{
    public int IDACCOUNTING_CLIENT { get; set; }
    public int IDACCOUNTING_COMPANY { get; set; }
    public string BANK { get; set; }
    public string BANK_SEAT { get; set; }
    public string IBAN { get; set; }
    public string PAYMENT { get; set; }
    public string ABI { get; set; }
    public string CAB { get; set; }
    public string ISTATCODE { get; set; }
    public string BOOKCODE { get; set; }
    public string BILLNOTE { get; set; }
    public bool SPESEINCASSO { get; set; }
    public Nullable<decimal> SPESEINCASSOVAL { get; set; }
    public bool ESENZIONEIVA { get; set; }
    public string ESENZIONEIVADESC { get; set; }
    public bool RIMBORSOKM { get; set; }
    public Nullable<decimal> RIMBORSOKMVAL { get; set; }
    public Nullable<decimal> RIMBORSOFORFAIT { get; set; }
    public System.DateTime CREATEDATE { get; set; }
    public System.DateTime MODIFYDATE { get; set; }
    public string SPLIT_PAYMENT { get; set; }
    public string LETTERA_DINTENTI { get; set; }
}

public partial class TCLIENT_BILL
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TCLIENT_BILL()
    {
        this.TCLIENT_BILL_DETAIL = new HashSet<TCLIENT_BILL_DETAIL>();
    }

    public int IDBILL { get; set; }
    public int IDBILL_COMPANY { get; set; }
    public int IDBILL_CLIENT { get; set; }
    public short IDBILL_YEAR { get; set; }
    public short IDBILL_MONTH { get; set; }
    public Nullable<int> BILL_NUM { get; set; }
    public System.DateTime BILL_DATE { get; set; }
    public double BILL_IMPORT { get; set; }
    public string BILL_NOTE { get; set; }
    public string BILL_NOTE_PRINT { get; set; }
    public string BILL_TYPE { get; set; }
    public bool BILL_RECEIVED { get; set; }
    public Nullable<double> BILL_IMPORT_RECEIVED { get; set; }
    public System.DateTime MACRODATE { get; set; }
    public Nullable<int> IDBILL_DATI_FATTURAZIONE { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<TCLIENT_BILL_DETAIL> TCLIENT_BILL_DETAIL { get; set; }
    public virtual TCLIENT TCLIENT { get; set; }
    public virtual TCLIENT_DATI_FATTURAZIONE TCLIENT_DATI_FATTURAZIONE { get; set; }
}

public partial class TCLIENT_BILL_DETAIL
{
    public int IDDETAIL { get; set; }
    public int IDDETAIL_BILL { get; set; }
    public int IDDETAIL_COMPANY { get; set; }
    public int IDDETAIL_CLIENT { get; set; }
    public short IDDETAIL_YEAR { get; set; }
    public short IDDETAIL_MONTH { get; set; }
    public Nullable<int> IDDETAIL_SERVICE { get; set; }
    public Nullable<int> IDDETAIL_ACTIVITY_BILLING { get; set; }
    public string DETAIL_TYPE { get; set; }
    public Nullable<double> DETAIL_PRICE { get; set; }
    public string DETAIL_NOTE { get; set; }
    public System.DateTime MACRODATE { get; set; }
    public Nullable<int> IDDETAIL_DATI_FATTURAZIONE { get; set; }

    public virtual TORDER_ACTIVITY_BILLING ACTIVITY_BILLING { get; set; }
    public virtual TCLIENT_DOMAIN_SERVICE DOMAIN_SERVICE { get; set; }
    public virtual TCLIENT TCLIENT { get; set; }
    public virtual TCLIENT_DATI_FATTURAZIONE TCLIENT_DATI_FATTURAZIONE { get; set; }
}

public partial class TCLIENT_DATI_FATTURAZIONE
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TCLIENT_DATI_FATTURAZIONE()
    {
        this.TCLIENT_DOMAIN_SERVICE = new HashSet<TCLIENT_DOMAIN_SERVICE>();
        this.TORDER_ACTIVITY_BILLING = new HashSet<TORDER_ACTIVITY_BILLING>();
        this.TCLIENT_BILL = new HashSet<TCLIENT_BILL>();
        this.TCLIENT_BILL_DETAIL = new HashSet<TCLIENT_BILL_DETAIL>();
    }

    public int IDDATI_FATTURAZIONE { get; set; }
    public int IDDATI_FATTURAZIONE_CLIENT { get; set; }
    public string NAME { get; set; }
    public string ADDRESS { get; set; }
    public string LOCALITY { get; set; }
    public string ZIPCODE { get; set; }
    public Nullable<int> IDDATI_FATTURAZIONE_PROVINCE { get; set; }
    public Nullable<int> IDDATI_FATTURAZIONE_STATE { get; set; }
    public string VATNUMBER { get; set; }
    public string FISCAL_CODE { get; set; }
    public string CODICEFATTURAZIONE { get; set; }
    public bool DATI_FATTURAZIONEHIDE { get; set; }
    public System.DateTime MACRODATE { get; set; }

    public virtual TCLIENT TCLIENT { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<TCLIENT_DOMAIN_SERVICE> TCLIENT_DOMAIN_SERVICE { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<TORDER_ACTIVITY_BILLING> TORDER_ACTIVITY_BILLING { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<TCLIENT_BILL> TCLIENT_BILL { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<TCLIENT_BILL_DETAIL> TCLIENT_BILL_DETAIL { get; set; }
}

public partial class TCLIENT_DOMAIN_SERVICE
{
    public int IDSERVICE { get; set; }
    public int IDSERVICE_DOMAIN { get; set; }
    public byte IDSERVICE_TYPE { get; set; }
    public Nullable<byte> IDSERVICE_SERVER { get; set; }
    public Nullable<byte> IDSERVICE_PLANNING { get; set; }
    public Nullable<System.DateTime> ACTIVATIONDATE { get; set; }
    public Nullable<System.DateTime> BILLDATE { get; set; }
    public Nullable<System.DateTime> ENDBILLDATE { get; set; }
    public Nullable<double> SERVICE_COST { get; set; }
    public Nullable<double> SERVICE_PRICE { get; set; }
    public string SERVICE_NOTE { get; set; }
    public bool SERVICE_HIDE { get; set; }
    public System.DateTime MACRODATE { get; set; }
    public Nullable<int> IDSERVICE_DATI_FATTURAZIONE { get; set; }

    public virtual TCLIENT_DOMAIN_SERVICE_TYPE DOMAIN_SERVICE_TYPE { get; set; }
    public virtual TCLIENT_DATI_FATTURAZIONE TCLIENT_DATI_FATTURAZIONE { get; set; }
}

public partial class TCLIENT_DOMAIN_SERVICE_PLANNING
{
    public byte IDPLANNING { get; set; }
    public string PLANNING { get; set; }
    public byte PLANNING_VALUE { get; set; }
    public bool PLANNING_HIDE { get; set; }
}

public partial class TCLIENT_DOMAIN_SERVICE_TYPE
{
    public byte IDTYPE { get; set; }
    public string TYPE { get; set; }
    public short TYPE_POS { get; set; }
    public bool TYPE_HIDE { get; set; }
}

public partial class TCOURSE_EDITION_MEMBER
{
    public int IDEDITION_LINK { get; set; }
    public int IDMEMBER_LINK { get; set; }
    public Nullable<byte> HOURNUM { get; set; }
    public Nullable<decimal> PERC { get; set; }
    public bool ATTESTATO { get; set; }
    public Nullable<short> ATTESTATONUM { get; set; }
    public System.DateTime CREATEDATE { get; set; }
    public Nullable<decimal> QUOTAPERS { get; set; }
    public Nullable<System.DateTime> MODIFYDATE { get; set; }

    public virtual TCOURSE_MEMBER TCOURSE_MEMBER { get; set; }
}

public partial class TCOURSE_MEMBER
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TCOURSE_MEMBER()
    {
        this.TCOURSE_EDITION_MEMBER = new HashSet<TCOURSE_EDITION_MEMBER>();
    }

    public int IDMEMBER { get; set; }
    public int IDMEMBER_CORPORATE { get; set; }
    public Nullable<int> IDMEMBER_CLIENT { get; set; }
    public Nullable<int> IDMEMBER_GROUP { get; set; }
    public string FIRSTNAME { get; set; }
    public string LASTNAME { get; set; }
    public Nullable<System.DateTime> BIRTHDATE { get; set; }
    public string BIRTHPLACE { get; set; }
    public string ADDRESS { get; set; }
    public string LOCALITY { get; set; }
    public Nullable<int> IDMEMBER_PROVINCE { get; set; }
    public string ZIPCODE { get; set; }
    public string TELEPHONE { get; set; }
    public string MOBILE { get; set; }
    public string FAX { get; set; }
    public string EMAIL { get; set; }
    public string FISCALCODE { get; set; }
    public string VAT { get; set; }
    public string PAYMENT { get; set; }
    public string BANK { get; set; }
    public string IBAN { get; set; }
    public string MANSIONE { get; set; }
    public bool MEMBERHIDE { get; set; }
    public System.DateTime CREATEDATE { get; set; }
    public System.DateTime MODIFYDATE { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<TCOURSE_EDITION_MEMBER> TCOURSE_EDITION_MEMBER { get; set; }
    public virtual TREGISTRY_PROVINCE TREGISTRY_PROVINCE { get; set; }
}

public partial class TORDER_ACTIVITY
{
    public int IDACTIVITY { get; set; }
    public Nullable<int> IDACTIVITY_ORDER { get; set; }
    public Nullable<int> IDACTIVITY_OFFER_ACTIVITY { get; set; }
    public byte IDCATEGORY { get; set; }
    public string CATEGORY { get; set; }
    public short IDACTIVITY_TYPE { get; set; }
    public string ACTIVITY_TYPE { get; set; }
    public string DESCRIPTION { get; set; }
    public string ACTIVITY_NOTE { get; set; }
    public Nullable<int> IDUSER_REG { get; set; }
    public Nullable<System.DateTime> REGDATE { get; set; }
    public Nullable<System.DateTime> STARTDATE { get; set; }
    public Nullable<int> IDUSER_RESP { get; set; }
    public Nullable<System.DateTime> EXPIRYDATE { get; set; }
    public Nullable<System.DateTime> ENDDATE { get; set; }
    public Nullable<double> HOUR { get; set; }
    public Nullable<double> SPRICE { get; set; }
    public byte IDACTIVITY_MODE { get; set; }
    public byte IDACTIVITY_STATUS { get; set; }
    public byte IDACTIVITY_PROGRESS { get; set; }
    public string WORKUSERS { get; set; }
    public bool MONITORING { get; set; }
    public Nullable<double> RIMBUSER { get; set; }
    public Nullable<double> IMPORTUSER { get; set; }
    public bool ACTIVITY_HIDE { get; set; }
    public System.DateTime MACRODATE { get; set; }

    public virtual TACTIVITY_TYPE TACTIVITY_TYPE { get; set; }
    public virtual TACTIVITY_TYPE_CATEGORY TACTIVITY_TYPE_CATEGORY { get; set; }
}

public partial class TORDER_ACTIVITY_BILLING
{
    public int IDBILLING { get; set; }
    public int IDBILLING_ACTIVITY { get; set; }
    public Nullable<byte> IDBILLING_STEP { get; set; }
    public string BILLING_DESC { get; set; }
    public byte IDBILLING_PERC { get; set; }
    public Nullable<double> BILLING_PERC { get; set; }
    public Nullable<decimal> BILLING_PRICE { get; set; }
    public Nullable<System.DateTime> BILLING_LIMIT_DATE { get; set; }
    public Nullable<System.DateTime> BILLING_DATE { get; set; }
    public Nullable<System.DateTime> BILLING_END_DATE { get; set; }
    public bool BILLING_HIDE { get; set; }
    public Nullable<int> IDBILLING_DATI_FATTURAZIONE { get; set; }

    public virtual TORDER_ACTIVITY ACTIVITY { get; set; }
    public virtual TORDER_ACTIVITY_BILLING_STEP ACTIVITY_BILLING_STEP { get; set; }
    public virtual TCLIENT_DATI_FATTURAZIONE TCLIENT_DATI_FATTURAZIONE { get; set; }
}

public partial class TORDER_ACTIVITY_BILLING_STEP
{
    public byte IDSTEP { get; set; }
    public byte IDSTEP_MODE { get; set; }
    public string STEP { get; set; }
    public Nullable<byte> STEP_POS { get; set; }
    public bool STEP_HIDE { get; set; }

    public virtual TORDER_ACTIVITY_BILLING_STEP TORDER_ACTIVITY_BILLING_STEP1 { get; set; }
    public virtual TORDER_ACTIVITY_BILLING_STEP TORDER_ACTIVITY_BILLING_STEP2 { get; set; }
}

public partial class TREGISTRY_PROVINCE
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TREGISTRY_PROVINCE()
    {
        this.TCLIENT = new HashSet<TCLIENT>();
    }

    public int IDPROVINCE { get; set; }
    public string PROVINCE { get; set; }
    public string PROVINCEACRONYM { get; set; }
    public bool PROVINCEHIDE { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<TCLIENT> TCLIENT { get; set; }
}

public partial class TREGISTRY_STATE
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TREGISTRY_STATE()
    {
        this.TCLIENT = new HashSet<TCLIENT>();
    }

    public int IDSTATE { get; set; }
    public string STATE { get; set; }
    public string STATECODE { get; set; }
    public bool STATEHIDE { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<TCLIENT> TCLIENT { get; set; }
}

public partial class udfTCLIENT_BILL_YM_Result
{
    public string COMPANY_SIGLA { get; set; }
    public string NAME { get; set; }
    public string ADDRESS { get; set; }
    public string ZIPCODE { get; set; }
    public string LOCALITY { get; set; }
    public string PROVINCE { get; set; }
    public string VATNUMBER { get; set; }
    public string FISCAL_CODE { get; set; }
    public Nullable<int> BILL_NUM { get; set; }
    public System.DateTime BILL_DATE { get; set; }
    public string PAYMENT { get; set; }
    public string BANK { get; set; }
    public string COORDINATE { get; set; }
    public Nullable<double> DETAIL_PRICE { get; set; }
    public string DETAIL_NOTE { get; set; }
    public string BILL_NOTE_PRINT { get; set; }
    public string DETAIL { get; set; }
    public Nullable<int> IDACTIVITY_TYPE { get; set; }
    public Nullable<bool> SPESEINCASSO { get; set; }
    public Nullable<decimal> SPESEINCASSOVAL { get; set; }
    public Nullable<int> VAT { get; set; }
    public string VATDESC { get; set; }
    public bool RIMBORSOKM { get; set; }
    public Nullable<double> VALORE_RIMBORSO { get; set; }
    public string DESCRIZIONE_RIMBORSO { get; set; }
}

public partial class udfTcourseEditionBilling_Result
{
    public Nullable<int> IDCLIENT { get; set; }
    public Nullable<int> IDBILLING_MEMBER { get; set; }
    public int IDBILLING_EDITION { get; set; }
    public Nullable<int> BILLING_NUM { get; set; }
    public string BILL_DATE { get; set; }
    public Nullable<double> BILLING_PRICE { get; set; }
    public Nullable<byte> BILLING_VAT { get; set; }
    public Nullable<short> EDITION_NUM { get; set; }
    public string COURSE { get; set; }
    public Nullable<short> HOURNUMTOTAL { get; set; }
    public Nullable<System.DateTime> MINDATE { get; set; }
    public Nullable<System.DateTime> MAXDATE { get; set; }
}
